---
# Install Nginx
- name: Install packages
  apt:
    name: "{{ webserver_packages }}"
    state: present
    update_cache: yes

# # Delete default Page in nginx
# - name: Clean artifact path
#   file:
#     state: absent
#     path: "{{ default_page }}"

# # Add group and user nginx
# - name: add group and user nginx
#   block:
#     - name: Add group "nginx"
#       group: 
#        name: nginx
#     - name: Add a new user "nginx"
#       user:
#         name: nginx
#         group: nginx
#         shell: /bin/bash

# Create directory for two pages
- name: —Åreate directory
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: directory
  loop: "{{ new_pages }}"

# Add config nginx
- name: Add base NGINX configuration file
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ ngnix_files }}"
  notify: Reload NGINX
