#For Linux group
- name: Install git and pyhton3
  import_tasks: install.yml
  become: true
  
#Install docker
- name: Install docker
  import_tasks: docker.yml
  become: true 

#  Optional sudo or wheel group for user hw20
# If the value "{{ group_sudo }}" is not specified, the group will not be added
- name: Optional sudo group for user hw20
  set_fact: sgroup="{{ group_sudo }}"
  when: group_sudo is defined

#Add user for linux group
- name: Add the user 'hw20' with a sh shell and '/opt/hw20' home directory
  ansible.builtin.user:
   name: "{{ item.name }}"
   shell: "{{ item.shell }}"
   home: "{{ item.home }}"
   groups: "{{ item.group }},{{ sgroup }}"
   state: present
  with_items:
    - "{{ users.hw20 }}"
  become: true

#Add users hw22_1 and hw22_2 for linux group
- name: Add the user 'hw22_1 and m hw22_2' with a sh shell and '/opt/hw22' home directory
  ansible.builtin.user:
   name: "{{ item.name }}"
   shell: "{{ item.shell }}"
   home: "{{ item.home }}"
   groups: "{{ item.groups }}"
   state: present
  loop: "{{ users_hw22 }}"
  no_log: false
  become: true

#Reset connection  
- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection  
  
#Pull public git repo
- name: Pull public git repo as user hw20 to /opt/hw20/
  ansible.builtin.git:
     repo: "{{ item.repo }}"
     dest: "{{ item.dest }}"
     clone: yes
  with_items:
   - "{{ git }}"
  become: yes
  tags: gitrepo
