
# find
- name: find out the number of users
  ansible.builtin.shell: getent passwd | grep user*
  register: userid
  ignore_errors: yes
  # no_logs: true

# Add Users  with 
- name: Block add Users
  block:
   - name: Add the users with a bash shell and '/home/user(*)' home directory
     ansible.builtin.user:
      name: "{{ item.name }}"
      shell: "{{ item.shell }}"
      home: "{{ item.home }}"
      groups: "{{ item.groups }}"
      password: "{{ password | password_hash('sha512') }}"
      state: present
     loop: "{{ users }}"
     tags: add_users
  when: userid.rc  == 1

# Reset connection  for users
- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection 
