pack_git_pyt:
 - { name: "git-", version: "1.8.3.1-23.el7_8" }
 - { name: "python3-", version: "3.6.8-18.el7" }
pack_docker:
 - { name: "docker-ce-", version: "20.10.6-3.el7" }
 - { name: "docker-ce-cli-", version: "20.10.6-3.el7" }
 - { name: "containerd.io-", version: "1.4.4-3.1.el7" }
url_key:
 - { url: "https://download.docker.com/linux/centos/docker-ce.repo", dest: "/etc/yum.repos.d/docer-ce.repo" }
pack_nginx:
 - { name: "nginx-", version: "1.16.1-3.el7" }
