
Vagrant.configure("2") do |config|

 config.vm.define "node1" do |node1|
  node1.vm.box = "ubuntu/focal64"
  node1.vm.network "public_network", ip: "192.168.1.31"
 end
 config.vm.define "node2" do |node2|
  node2.vm.box = "centos/7"
  node2.vm.network "public_network", ip: "192.168.1.32"
 end
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end