---
#Node list

all:
 hosts:
  Group1:
   hosts:
    192.168.1.31:
  Group2:
   hosts:
    192.168.1.32:
  Group3:
   hosts:
    192.168.1.33:
 vars:
  ansible_user: vagrant
  ansible_ssh_private_key_file: /home/sewd/.ssh/id_rsa
