#Linux vars
ansible_user: vagrant
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
cr_file:
 - { content: "", dest: "/opt/hw23_test_file", owner: "root", group: "root",  mode: "0644"  }
symlink:
 - { src: "/etc/hosts", dest: "/opt/hw23_link", owner: "root", group: "root",  mode: "0644"  }