# Install Packages for Docker to Ubuntu
- name: "Install Docker on Ubuntu"
  block:
    - name: "Set up the repository"
      ansible.builtin.package:
       name: "{{ item.name }}={{ item.version }}"
       update_cache: yes
      with_items:
       - "{{ packages }}"

    - name: "Add GPG key"
      ansible.builtin.apt_key:
       url: "{{ item.url }}"
       state: present
      with_items:
       - "{{ url_key}}"

    - name: "Add repos"
      ansible.builtin.apt_repository:
       repo: "{{ repo }}"
       state: present        
  when: ansible_facts['os_family'] == "Debian"

# Install Packages to CentOS
- name: "Install Docker on CentOS"
  block:
    - name: "Add Docker repo"
      ansible.builtin.get_url:
       url: "{{ item.url }}"
       dest: "{{ item.dest }}"
      with_items: "{{ url_key }}"
 
    - name: Install epel
      yum: 
       name: epel-release 
       state: present
  when: ansible_facts['os_family'] == "RedHat"  

# Install Docker and Nginx,  git and Pyhton
- name: "Install Docker and Nginx,  git and Pyhton"
  ansible.builtin.package:
   name: "{{ item.name }}{{ item.version }}"
   update_cache: yes
  with_items:
    - "{{ pack_git_pyt }}" 
    - "{{ pack_docker }}"
    - "{{ pack_nginx }}"
  register: service_change
  notify: 
     - Docker started
     - nginx started
     - Docker restarted
     - nginx restarted
  
