---
- hosts: all
  tasks:
  - name: Install packages
    become: true
    ansible.builtin.package:
      name:
        - software-properties-common
        - apt-transport-https
      state: latest
  
  - name: add repo 
    become: true
    ansible.builtin.apt_repository:
      repo: 'ppa:openjdk-r/ppa'
  
  - name: Install packages jdk
    become: true
    ansible.builtin.package:
      name:
        - openjdk-8-jdk
      state: latest
