#Start service systemd logging
- name: Start logsysd
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  become_user: root
  loop:
   - logsysd.timer
   - logsysd.service
  listen: "logsysd start"
