---
#Get info from files
- name: "Get variables from file"
  import_tasks: template.yml

#Copy to Ubuntu
- name: "Copy files to hosts"
  become: true
  become_user: root
  ansible.builtin.copy:
   src: /home/engelko/DevOps_course/Bash_scripts/HW20/roles/hw202/files/curl_7.68.deb
   dest: /tmp/curl_7.68.deb
   owner: hw20
   mode: 0744
  when: ansible_facts['os_family'] == "Debian"
  tags: cp_curl_cent
  
#Copy to CentOS
- name: "Copy files to hosts"
  become: true
  become_user: root
  ansible.builtin.copy:
   src: /home/engelko/DevOps_course/Bash_scripts/HW20/roles/hw202/files/curl-7.29.rpm
   dest: /tmp/curl-7.29.rpm
   owner: hw20
   mode: 0744
  when: ansible_facts['os_family'] == "RedHat"
  tags: cp_curl_cent
  
#Install Curl on Ubuntu
- name: "Install curl .deb package"
  become: true
  ansible.builtin.apt:
    deb: /tmp/curl_7.68.deb
    state: present
    update_cache: yes
    install_recommends: yes 
  when: ansible_facts['os_family'] == "Debian"
  tags: install_curl_ubn
  ignore_errors: yes
  
#Install Curl on CentOS
- name: "Install curl .rpm package"
  become: true
  ansible.builtin.yum:
    name: /tmp/curl-7.29.rpm
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"
  tags: install_curl_cent

#Copy sh files to hosts
- name: "Push sh to hosts"
  import_tasks: templatesysd.yml

# #Start service systemd logging
# - name: Start and Enabled timer logsysd
#   ansible.builtin.service:
#     name: logsysd.timer
#     state: started
#     enabled: yes

# - name: Start and Enabled service logsysd
#   ansible.builtin.service:
#     name: logsysd.service
#     state: started
#     enabled: yes
- name: Start logsysd
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  become_user: root
  loop:
   - logsysd.timer
   - logsysd.service