# tasks hw24
- hosts: linux
  strategy: free
  tags: hw26
  roles:
   - hw26
  
  # tags: hw23
  # roles:
  #  - role: hw23
  #    vars: 
  #      fakepam: abc
  #  - role: hw23
  #    vars: 
  #       fakepam: cba
 
# - hosts: localhost
#   tags: cpfile
#   roles:
#    - cpfile

# - hosts: linux
#   tags: hw24
#   roles:
#    - hw24
