pipeline {
  agent any
  stages {
    stage('Checkout Scm') {
      steps {
        git(credentialsId: 'engelko', url: 'git@github.com:Engelko/DevOps_course.git')
      }
    }

    stage('No Converter-0') {
      steps {
        echo 'No converter for Builder: com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher'
      }
    }

  }
  parameters {
    string(name: 'VERSION', defaultValue: 'v1', description: null)
  }
  triggers {
    upstream(upstreamProjects: 'tasktwo, ', threshold: hudson.model.Result.SUCCESS)
  }
}