# Copy  files to hosts for systemd logs
- name: "Template files to hosts"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  with_items:
   - "{{ deamon_templates }}"
