#Linux vars
ansible_user: vagrant
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
users:
 hw20:
  name: hw20
  shell: /bin/sh
  home: /opt/hw20
git:
  repo: 'https://github.com/githubtraining/training-manual.git'
  dest: /opt/hw20/git/
var_template:
 - { src: "main.j2", dest: "/tmp/HW20_FILE_INFO", owner: "hw20", mode: "0644" }
