#Linux vars
ansible_user: vagrant
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
cr_file:
 - { content: "", dest: "/opt/hw23_test_file", owner: "root", group: "root",  mode: "0644"  }
symlink:
 - { src: "/etc/hosts", dest: "/opt/hw23_link", owner: "root", group: "root",  mode: "0644"  }
docker: docker
nginx: nginx
users_hw24:
 - { name: hw24, groups: "docker", shell: /bin/sh, home: /opt/hw24}
user_ssh: hw24
users:
 - { name: user1, groups: "docker", shell: /bin/bash, home: /home/user1}
 - { name: user2, groups: "docker", shell: /bin/bash, home: /home/user2}
 - { name: user3, groups: "docker", shell: /bin/bash, home: /home/user3}
datefile:
 - { src: "/tmp/update/date.txt", dest: "/home/vagrant/date.txt", owner: "root", group: "root",  mode: "0644"  }
var_hw26: ed

