---
#Get info from files
- name: "Get variables from file"
  import_tasks: template.yml

#Copy to group linux
- name: "Copy files to hosts"
  become: true
  become_user: root
  ansible.builtin.copy:
   src: "{{ item }}"
   dest: "{{ dest_curl }}"
   owner: hw20
   mode: 0744
  loop: 
   - "{{ src_curl }}"

  
#Install Curl on Ubuntu
- name: "Install a .deb package "
  become: true
  ansible.builtin.apt:
    deb: "{{ dest_curl }}"
    state: present
    update_cache: yes
    install_recommends: yes
  when: ansible_facts['os_family'] == "Debian"
 
  #Install Curl on CentOS
- name: "Install a .rpm package"
  become: true
  ansible.builtin.yum:
    name: "{{ dest_curl }}"
    state: present
    update_cache: yes
    allow_downgrade: yes
  when: ansible_facts['os_family'] == "RedHat"
  
  
