version: '3.2'

volumes:
  jenkins-home:

services:
  jenkins:
    image: "${MY_REGISTARY}jenkins-docker"
    build: .
    restart: unless-stopped
    ports:
        - 8080:8080
        - 50000:50000
    privileged: true
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    container_name: jenkins-docker
