#Linux vars
ansible_user: vagrant
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
users:
 hw20:
  name: hw20
  shell: /bin/sh
  home: /opt/hw20
  group: docker
users_hw22:
 - { name: hw22_1, groups: "docker", shell: /bin/sh, home: /opt/hw22_1}
 - { name: hw22_2, groups: "docker", shell: /bin/sh, home: /opt/hw22_2}
git:
  repo: 'https://github.com/githubtraining/training-manual.git'
  dest: /opt/hw20/git/
var_template:
 - { src: "main.j2", dest: "/tmp/HW20_FILE_INFO", owner: "hw20", mode: "0644" }
deamon_templates:
 - { src: "sysdlogging.sh", dest: "/tmp/logdeamon.sh", owner: "root", mode: "0744" }
 - { src: "logsysd.service.j2", dest: "/lib/systemd/system/logsysd.service", owner: "root", mode: "0644" }
 - { src: "logsysd.timer.j2", dest: "/lib/systemd/system/logsysd.timer", owner: "root", mode: "0644" }
 - { src: "logrotate.j2", dest: "/etc/logrotate.d/logsysd", owner: "root", mode: "0644" }
iphosts_template:
 - { src: "{{ iphosts }}.txt", dest: "/tmp", owner: "hw20", mode: "0644" }
# Templates Variables
deamon_var:
 OnUnitActiveSec: 30s
 OnBootSec: 10s
 ExecStart: /tmp/logdeamon.sh
period: weekly
rotate: 5
compres: compress  # If the value is not specified, the compress will not be added / compress
